/**
 * Simple SotM API
 * SotM API that handles data for my app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dahlgrensm@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.DecksOwned
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DecksOwnedApi {

  /**
   * Posts a new decksOwned to the DB 
   * 
   * Expected answers:
   *   code 200 : String (Deck added)
   *   code 400 :  (bad input parameter)
   * 
   * @param decksOwned deck object from DB
   */
  def apiDecksOwnedPost(decksOwned: Option[DecksOwned] = None): ApiRequest[String] =
    ApiRequest[String](ApiMethods.POST, "https://localhost", "/api/decksOwned", "application/x-www-form-urlencoded")
      .withBody(decksOwned)
      .withSuccessResponse[String](200)
      .withErrorResponse[Unit](400)
        /**
   * Gets decksOwned from the DB 
   * 
   * Expected answers:
   *   code 201 :  (hero added)
   *   code 400 :  (invalid input, object invalid)
   *   code 409 :  (an existing item already exists)
   */
  def getDecksOwned(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/api/decksOwned", "application/json")
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](409)
      

}

