/**
 * Simple SotM API
 * SotM API that handles data for my app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dahlgrensm@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Environment
import io.swagger.client.model.Villain
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object EnvironmentApi {

  /**
   * Gets all env from the DB 
   * 
   * Expected answers:
   *   code 200 : Seq[Environment] (Array of env)
   *   code 400 :  (bad input parameter)
   */
  def apiEnvironmentPost(): ApiRequest[Seq[Environment]] =
    ApiRequest[Seq[Environment]](ApiMethods.POST, "https://localhost", "/api/environment", "application/json")
      .withSuccessResponse[Seq[Environment]](200)
      .withErrorResponse[Unit](400)
        /**
   * Adds an Env to the DB 
   * 
   * Expected answers:
   *   code 201 :  (hero added)
   *   code 400 :  (invalid input, object invalid)
   *   code 409 :  (an existing item already exists)
   * 
   * @param inventoryItem Inventory item to add
   */
  def getEnv(inventoryItem: Option[Villain] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/api/environment", "application/x-www-form-urlencoded")
      .withBody(inventoryItem)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](409)
      

}

