/**
 * Simple SotM API
 * SotM API that handles data for my app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dahlgrensm@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Hero
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object HeroApi {

  /**
   * Adds a hero to the DB 
   * 
   * Expected answers:
   *   code 201 :  (hero added)
   *   code 400 :  (invalid input, object invalid)
   *   code 409 :  (an existing item already exists)
   * 
   * @param name name of hero to add
   */
  def addHero(name: Option[Hero] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/api/hero", "application/x-www-form-urlencoded")
      .withBody(name)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](409)
        /**
   * By passing in the appropriate options, you can search for heroes in the system 
   * 
   * Expected answers:
   *   code 200 : Seq[Hero] (Array of heroes)
   *   code 400 :  (bad input parameter)
   */
  def apiHeroGet(): ApiRequest[Seq[Hero]] =
    ApiRequest[Seq[Hero]](ApiMethods.GET, "https://localhost", "/api/hero", "application/x-www-form-urlencoded")
      .withSuccessResponse[Seq[Hero]](200)
      .withErrorResponse[Unit](400)
      

}

