/**
 * Simple SotM API
 * SotM API that handles data for my app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dahlgrensm@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.User
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object LoginApi {

  /**
   * Post a user for auth 
   * 
   * Expected answers:
   *   code 200 : String (auth successful)
   *   code 400 :  (bad input parameter)
   * 
   * @param auth auth
   */
  def apiLoginPost(auth: Option[User] = None): ApiRequest[String] =
    ApiRequest[String](ApiMethods.POST, "https://localhost", "/api/login", "application/x-www-form-urlencoded")
      .withBody(auth)
      .withSuccessResponse[String](200)
      .withErrorResponse[Unit](400)
      

}

