/**
 * Simple SotM API
 * SotM API that handles data for my app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dahlgrensm@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.User
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object UsersApi {

  /**
   * Add a user 
   * 
   * Expected answers:
   *   code 200 : String (User created)
   *   code 400 :  (bad input parameter)
   * 
   * @param user add a new user
   */
  def apiUserPost(user: Option[User] = None): ApiRequest[String] =
    ApiRequest[String](ApiMethods.POST, "https://localhost", "/api/user", "application/x-www-form-urlencoded")
      .withBody(user)
      .withSuccessResponse[String](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 : String (user deleted)
   *   code 400 :  (Invalid input value)
   * 
   * @param username 
   */
  def deleteUser(username: String): ApiRequest[String] =
    ApiRequest[String](ApiMethods.DELETE, "https://localhost", "/api/user", "multipart/form-data")
      .withPathParam("username", username)
      .withSuccessResponse[String](200)
      .withErrorResponse[Unit](400)
      

}

