/**
 * Simple SotM API
 * SotM API that handles data for my app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dahlgrensm@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Villain
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object VillainApi {

  /**
   * By passing in the appropriate options, you can add villains to the system 
   * 
   * Expected answers:
   *   code 200 : Seq[Villain] (Villain added to DB)
   *   code 400 :  (bad input parameter)
   * 
   * @param name name of villain to add
   */
  def apiVillainPost(name: Option[Villain] = None): ApiRequest[Seq[Villain]] =
    ApiRequest[Seq[Villain]](ApiMethods.POST, "https://localhost", "/api/villain", "application/json")
      .withBody(name)
      .withSuccessResponse[Seq[Villain]](200)
      .withErrorResponse[Unit](400)
        /**
   * Gets all villains 
   * 
   * Expected answers:
   *   code 201 :  (Array of villains)
   *   code 400 :  (invalid input, object invalid)
   *   code 409 :  (an existing item already exists)
   */
  def getVillain(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/api/villain", "application/x-www-form-urlencoded")
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](409)
      

}

